In [15]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

# pandas的数据结构介绍

## Series

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4, 7, -5 ,3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['b'] = 6

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [13]:
obj2[obj2>0]

d    4
b    6
c    3
dtype: int64

In [14]:
obj2 * 2

d     8
b    12
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d     54.598150
b    403.428793
a      0.006738
c     20.085537
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In [19]:
sdata = {'Ohio':35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [20]:
obj3=Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [25]:
states = ['California' ,'Ohio', 'Oregon', 'Texas']

In [26]:
obj4 = Series(sdata, index=states)

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
pd.isnull(obj3)

Ohio      False
Texas     False
Oregon    False
Utah      False
dtype: bool

In [29]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [32]:
obj4.name = 'population'

In [33]:
obj4.index.name = 'state'

In [34]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [36]:
obj.index=['Bob', 'Steve', 'Jeff', 'Ryan']

In [37]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

常用字典来生成DataFrame

常见的方式还有嵌套字典

## 索引对象

与集合不同，pandas的index可以包含重复的标签

# 基本功能

## 重新索引

In [38]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [39]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [40]:
obj2 = obj.reindex(['a','b','c','d','e'])  #会根据新索引进行重新排列

In [41]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [42]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [43]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [44]:
obj3.reindex(range(6),method='ffill') #缺失值用前面的值来填充

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [46]:
frame = DataFrame(np.arange(9).reshape((3,3)),
                index=['a', 'c', 'd'],
                columns=['Ohio', 'Texas', 'California'])

In [47]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [48]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [49]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [50]:
states=['Texas', 'Utah', 'California']

In [51]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## 丢弃指定轴上的项

In [52]:
obj = Series(np.arange(5.), index=['a','b','c','d','e'])

In [53]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [54]:
new_obj = obj.drop('c')

In [55]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [56]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [57]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [58]:
obj.drop('c',inplace=True)  #就地修改，不产生新对象

In [59]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## 索引、选取和过滤

可以用标签名称、也可以用索引序列

## 用loc和iloc进行选取(标签索引和整数索引)

注意：标签索引最后面的一项是包括在内的（不像整数索引）

In [60]:
data = DataFrame(np.arange(16).reshape((4,4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns = ['one', 'two', 'three', 'four'])

In [61]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [62]:
data.loc['Colorado',['two','three']]  #先选行，再选列

two      5
three    6
Name: Colorado, dtype: int32

In [63]:
data.iloc[1,[1,2]]  #同样的效果

two      5
three    6
Name: Colorado, dtype: int32

In [64]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [65]:
data.iloc[1,1]

5

In [66]:
data.iloc[[0,2],[1,3]]

two  four
Ohio    1     3
Utah    9    11

In [67]:
data.loc[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [68]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

## 整数索引

In [69]:
ser = Series(np.arange(3.))

In [70]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [72]:
ser.iloc[-1]

2.0

In [73]:
ser2 = Series(np.arange(3.), index=['a', 'b', 'c'])

In [74]:
ser2[-1]

2.0

## 算术运算和数据对齐

In [76]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd','e'])

In [77]:
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1],
           index=['a', 'c', 'e','f','g'])

In [78]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [79]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [80]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [81]:
df1 = DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),
               index=['Ohio', 'Texas', 'Colorado'])

In [82]:
df2 = DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),
               index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [83]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [84]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [85]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

## 在算数方法中填充值

In [86]:
df1 = DataFrame(np.arange(12.).reshape((3,4)),
               columns=list('abcd'))

In [87]:
df2 = DataFrame(np.arange(20.).reshape((4,5)),
               columns=list('abcde'))

In [88]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [89]:
df2.loc[1,'b']

6.0

In [90]:
df2.loc[1,'b']=np.nan

In [91]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [92]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [93]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [94]:
df1.add(df2)

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [95]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [96]:
1/df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [97]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [98]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## DataFrame和Series之间的运算

In [99]:
arr = np.arange(12.).reshape((3,4))

In [100]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [101]:
arr[0]

array([0., 1., 2., 3.])

In [102]:
arr-arr[0]  #每一行都会减去第一行的值

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [103]:
frame = DataFrame(np.arange(12.).reshape((4,3)),
                 columns=list('bde'),
                 index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [104]:
series = frame.iloc[0]

In [105]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [106]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [107]:
frame-series  #索引匹配以后，每一行对其进行减法

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [108]:
series2 = Series(range(3), index=['b','e','f'])

In [109]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [110]:
series3 = frame['d']

In [111]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [112]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [113]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 函数应用和映射

In [114]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'),
                 index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [115]:
frame

b         d         e
Utah    0.654425  0.561780 -0.116629
Ohio   -0.986740 -0.478676 -1.715301
Texas  -0.319083 -0.274480 -1.973236
Oregon -0.756197 -2.152154 -0.383012

In [116]:
np.abs(frame)

b         d         e
Utah    0.654425  0.561780  0.116629
Ohio    0.986740  0.478676  1.715301
Texas   0.319083  0.274480  1.973236
Oregon  0.756197  2.152154  0.383012

In [117]:
f = lambda x: x.max()-x.min()

In [118]:
frame.apply(f)

b    1.641166
d    2.713934
e    1.856608
dtype: float64

In [119]:
frame.apply(f, axis=1)

Utah      0.771054
Ohio      1.236625
Texas     1.698756
Oregon    1.769142
dtype: float64

In [120]:
def f(x):
    return Series([x.min, x.max()], index=['min', 'max'])

In [121]:
frame.apply(f)

b  \
min  <bound method Series.min of Utah      0.654425...   
max                                           0.654425   

                                                     d  \
min  <bound method Series.min of Utah      0.561780...   
max                                            0.56178   

                                                     e  
min  <bound method Series.min of Utah     -0.116629...  
max                                          -0.116629

In [122]:
format = lambda x:'%.2f' % x  #保留两位小数

In [123]:
frame.applymap(format)

b      d      e
Utah     0.65   0.56  -0.12
Ohio    -0.99  -0.48  -1.72
Texas   -0.32  -0.27  -1.97
Oregon  -0.76  -2.15  -0.38

In [124]:
frame['e'].map(format)

Utah      -0.12
Ohio      -1.72
Texas     -1.97
Oregon    -0.38
Name: e, dtype: object

## 排名和排序

In [125]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])

In [126]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [127]:
frame = DataFrame(np.arange(8).reshape((2,4)),
                 index=['three','one'],
                 columns=['d', 'a', 'b', 'c'])

In [128]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [129]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [130]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [131]:
obj = Series([4,7,-3,2])

In [132]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [133]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])

In [135]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [136]:
frame = DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [137]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [138]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [139]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [140]:
obj = Series([7,-5,7,4,2,0,4])

In [141]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [142]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

## 带有重复标签的轴索引

简单

# 汇总和计算描述统计

In [144]:
df = DataFrame([[1.4,np.nan],[7.1,-4.5],
               [np.nan,np.nan],[0.75,-1.3]],
              index=['a','b','c','d'],
              columns=['one','two'])

In [145]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [146]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [147]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [148]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [149]:
df.idxmax()

one    b
two    d
dtype: object

In [150]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [151]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

## 相关系数和协方差

In [ ]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [ ]:
price = DataFrame({ticker:data['Adj Close']
                  for ticker, data in all_data.items()})
volume = DataFrame({ticker:data['Volume']
                   for ticker, data in all_data.items()})